### ISSUE TITLE
Final pre-announcement tweaks

### ISSUE THREAD

**Issue by durack1** [aims-group/publication-site#130]
Hi @mauzey1, we've been finalizing the text for the publication page announcement email and have some minor tweaks to request

- [x] Remove "keyword" entry from the CMIP5/6 form
- [x] Expand "variable" entry across width for both CMIP5/6 forms
- [x] Populate "variable" form with the CMOR name and long name e.g. "thetao - Sea Water Potential Temperature" sourced from the cmip6-cmor-tables repo
- [x] Add CMIP6 realms across both CMIP5 and CMIP6 e.g. "atmos - Atmosphere" full info in [CMIP6_CVs](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_realm.json)
- [ ] Update source_id/models in CMIP6 form - is this dynamically updated?

A dummy of what we hope these pages to look like (at least the layout, I didn't populate the variable field for e.g.) is below
![Screenshot_2021-05-21 New Publication](https://user-images.githubusercontent.com/3229632/119180916-c7963b80-ba25-11eb-9968-cf012c3e848d.png)

@taylor13 ping

**Comment by durack1** [comment]
@mauzey1 in addition we wanted to tweak the text at [metaForm.html](https://github.com/aims-group/publication-site/blob/abb5cfc308d417e6130b90627aa1a18f601b15d7/templates/snippets/metaForm.html#L3) to

`Please click on the relevant CMIP era tabs below. Optional additional information about the models, experiments, variables, and other characteristics of data used in your study is also invited.`

**Comment by durack1** [comment]
Hi @mauzey1 we were hoping (belatedly) to send out this announcement email, is there a chance the tweaks above could be completed this week?

**Comment by mauzey1** [comment]
@durack1 I will aim to have these changes online by the middle of Thursday.

**Comment by durack1** [comment]
@mauzey1 perfect, I will aim to send this email close to that time.

**Comment by mauzey1** [comment]
@durack1 So you want the realms from CMIP6 to also be used for CMIP5 when submitting a publication?

**Comment by durack1** [comment]
@mauzey1 yeah that seemed the most logical thing to do, map everything into the most modern formats/names. Is there an impact on the previously registered info?

**Comment by mauzey1** [comment]
@durack1 Adding realms for CMIP5 shouldn't impact the current CMIP5 entries, but I will need to update the realm for the CMIP6 entries to match the new format.

Would this new format apply to the CMIP5 variables?  Do you want the CMIP6 variables to be used for CMIP5, too?

**Comment by durack1** [comment]
@mauzey1 thanks for these detailed queries, I believe that the CMIP6 variables are a superset of the CMIP5 variables (with more added in CMIP6), so yes, let's use the CMIP6 entries across both.

Out of curiosity, how many of the ~1200 existing publications provided variable etc information? Many?

**Comment by mauzey1** [comment]
@durack1 Do the CMIP5 variables have a name and description similar to the CMIP6 variables?  The current CMIP5 variables listed look like the variable descriptions for CMIP6.  Do we just mix the CMIP5 variables as they are with the CMIP6 variables?

**Comment by mauzey1** [comment]
@durack1 Continuing from my previous comment...
There are CMIP5 variables that match the description of several CMIP6 variables.

For example, `surface upwelling shortwave flux in air` from CMIP5 is also the description of several CMIP6 variables.
```
         'rsus - Surface Upwelling Shortwave Flux In Air',
         'rsusIs - Surface Upwelling Shortwave Flux In Air',
         'rsusLut - Surface Upwelling Shortwave Flux In Air',
         'siflswutop - Surface Upwelling Shortwave Flux In Air',
```

**Comment by durack1** [comment]
@mauzey1 apologies telcos distracted me this afternoon.

Yes, the CMIP6 variables began from the CMIP5 variables, with some considerable long name cleanups, in addition to adding completely new variables for CMIP6, so let's go with CMIP6 as the standard variables as in most cases they include all the previous era quantities

**Comment by mauzey1** [comment]
@durack1
So should we keep the original CMIP5 variables in the list alongside the CMIP6 variables, or should we replace the existing CMIP5 variables with their CMIP6 equivalent?  There are numerous publications on the site that have variables already listed so we can't just get rid of the original CMIP5 variables without replacing them.

**Comment by mauzey1** [comment]
Here's the list of all the CMIP6 variables that I gathered from the tables.

https://github.com/mauzey1/publication-site/blob/8ae82591a3f5cd4edb5687eda986b09509f3f9ce/scripts/variable.py#L150

**Comment by mauzey1** [comment]
Here's what the submission page now looks like for CMIP6.

![Screenshot_2021-05-26 New Publication](https://user-images.githubusercontent.com/42009431/119745658-6ca87e00-be43-11eb-9319-16e96e9f28fc.png)

**Comment by durack1** [comment]
Perfect, that looks great (on mobile) will take another peek on a bigger screen later. Did you want to merge into master? It looks right from a quick scan

**Comment by mauzey1** [comment]
I think I have gotten most of the requested changes done for this issue so I will make a pull request.  I do however plan to merge the CMIP5 and CMIP6 variable sets.  I plan to completely remove the 'keyword' field from the publication database; the current changes only hide it from view.

**Comment by durack1** [comment]
Perfect, thanks @mauzey1 exactly what is needed, a cleanup of the database alongside this visual tweak. Thanks again for this, looking forward to announcing it

**Comment by mauzey1** [comment]
@durack1 Here's an example of the CMIP5 and CMIP6 variables combined
![Screenshot_2021-05-27 New Publication](https://user-images.githubusercontent.com/42009431/119917222-f8d9a480-bf1a-11eb-8444-ab56501957d7.png)

This commit merges the two lists together.  https://github.com/mauzey1/publication-site/commit/901aaed733af23d81afa408a203fd1274d0fbc11

Would you like me to merge this change?

**Comment by durack1** [comment]
@mauzey1 apologies I mustn't have been clear. Rather than bothering with the CMIP5 variables, my suggestion was just to use the CMIP6 variables for each. Even though some of the CMIP6 variables didn't exist in CMIP5, it's more simple to use the CMIP6 variable id's (e.g. tos) and long names (e.g. Sea Surface Temperature) as they have been more thoroughly vetted to be descriptively correct

**Comment by mauzey1** [comment]
@durack1 I wasn't sure how to merge the CMIP5 and CMIP6 variables until I found that the CMIP5 variable names in the form matched the standand names in the old CMIP5 tables.  Thankfully, I kept the old tables for CMIP5 in the [xml-cmor3-database repo](https://github.com/PCMDI/xml-cmor3-database/tree/master/src/old_tables).  I will need to replace the CMIP5 variable names listed for publications with the new names.  I will try to finish this by the end of today.

**Comment by durack1** [comment]
@mauzey1 excellent thanks. If I was planning to merge, I would use the CMOR names (e.g. tos) and then use the standard names from the cmip6-cmor-tables, I believe this would provide almost complete coverage

**Comment by durack1** [comment]
So just as an example, the [CMIP5 tos variable, with long_name "Sea Surface Temperature"](https://github.com/PCMDI/cmip5-cmor-tables/blob/master/Tables/CMIP5_Omon#L2878-L2901), should map onto the [CMIP6 tos variable, long_name "Sea Surface Temperature"](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Omon.json#L4625-L4641)

**Comment by mauzey1** [comment]
@durack1 
I was able to find most of the CMIP5 variables in the CMIP5 tables by searching for the standard names of the variables.  I needed to replace spaces with underscores to match the stings.  However, there were some variables that I couldn't find.  Below is a list of them.

- atmosphere_convective_mass_flux
- eastward_sea_ice_velocity
- northward_sea_ice_velocity
- ocean_chlorophyll
- snow_temperature
- surface_albedo
- water_sublimation_flux
- Other

I couldn't find exact matches for these variables with any of the standard names listed in the CMIP5 tables.  Do `northward_derivative_of_eastward_sea_ice_velocity` and `eastward_derivative_of_northward_sea_ice_velocity` mean `eastward_sea_ice_velocity` and `northward_sea_ice_velocity` respectively?  `surface_albedo` did match the `albsn` variable in CMIP6.  I also found `water_sublimation_flux` in the dreq.xml file of the data request used to create the CMIP6 tables.

Do I just leave these variables as they are in the publication submission form?

Is `Other` just a placeholder for variables that we currently don't know about?  Do we still need it?

**Comment by durack1** [comment]
@mauzey1 great, this is real progress, I have attempted to link CMIP5 -> CMIP6 below


- atmosphere_convective_mass_flux [mc, Amon](http://clipc-services.ceda.ac.uk/dreq/u/bab117b8-e5dd-11e5-8482-ac72891c3257.html)
- eastward_sea_ice_velocity [siu, SImon](http://clipc-services.ceda.ac.uk/dreq/u/7147b8fe-faa7-11e6-bfb7-ac72891c3257.html)
- northward_sea_ice_velocity [siv, SImon](http://clipc-services.ceda.ac.uk/dreq/u/71237944-faa7-11e6-bfb7-ac72891c3257.html)
- ocean_chlorophyll [chl, Omon](http://clipc-services.ceda.ac.uk/dreq/u/ba9fb75c-e5dd-11e5-8482-ac72891c3257.html)
- snow_temperature [sitemptop, SImon](http://clipc-services.ceda.ac.uk/dreq/u/711075e2-faa7-11e6-bfb7-ac72891c3257.html)
- surface_albedo (I am assuming this is an atmos variable) [albdiffbnd](http://clipc-services.ceda.ac.uk/dreq/u/7b301206-a220-11e6-a33f-ac72891c3257.html)
- water_sublimation_flux (again assuming atmos) [sbl, Amon](http://clipc-services.ceda.ac.uk/dreq/u/bab6b948-e5dd-11e5-8482-ac72891c3257.html)

Let me know if it's not clear above. @taylor13 happy for any corrections you may have noticed.

As I noted the CMIP6 data request (variable definitions) are more specific than their CMIP5 counterparts, so going with these should cover usages instances

I don't think "other" is useful, so let's remove it

**Comment by mauzey1** [comment]
@durack1 
I've replaced the above variables with their CMIP6 equivalent.  However, I have also ran into more CMIP5 variables that I couldn't find a CMIP6-equivalent for.  For these variables, I used the output name and long name from the CMIP5 tables.

- global average sea level change: 'zosga - Global Average Sea Level Change'
- mole fraction of ozone in air: 'tro3 - Mole Fraction of O3'
- northward ocean heat transport due to bolus advection: 'hfbasinba - Northward Ocean Heat Transport due to Bolus Advection'
- northward ocean heat transport due to diffusion: 'hfbasindiff - Northward Ocean Heat Transport due to Diffussion'
- sea ice area fraction: 'sic - Sea Ice Area Fraction'
- sea ice thickness: 'sit - Sea Ice Thickness'
- sea ice transport across line: 'transifs - Sea Ice Mass Transport Through Fram Strait'
- sea ice x velocity: 'usi - X-Component of Sea Ice Velocity'
- sea ice y velocity: 'vsi - Y-Component of Sea Ice Velocity'
- sea surface temperature: 'tso - Sea Surface Temperature'
- sea water potential density: 'rhopoto - Sea Water Potential Density'
- surface downward x stress: 'strairx - X-Component of Atmospheric Stress On Sea Ice'
- surface downward y stress: 'strairy - Y-Component of Atmospheric Stress On Sea Ice'
- time: 'toffset - Offset Time'
- water evaporation flux: 'evap - Water Evaporation Flux from Sea Ice'

However, some of these variables have multiple versions.  For example, `mole fraction of ozone in air` has [`tro3`](https://github.com/PCMDI/cmip5-cmor-tables/blob/7afc846ab5560b63e142ac371c38d7798cbaf8ab/Tables/CMIP5_Amon#L1958-L1968) and [`tro3Clim`](https://github.com/PCMDI/cmip5-cmor-tables/blob/7afc846ab5560b63e142ac371c38d7798cbaf8ab/Tables/CMIP5_Amon#L1983-L1993).  I only chose one of the choices for each variable if multiple versions were present.  How would you like these variables handled?

I also had to make additional changes to the CMIP6 variables.  In the previous changes, I used the standard name rather than the long name.  This will be corrected in the next pull request.  I also removed the variable choice `Other` from the menu.

**Comment by durack1** [comment]
@mauzey1 thanks, unpeeling the onion indeed!

Rather than me providing matches first up, do we have any instances of existing publication database entries that list any of these variables against their registration? If yes, then I will provide a CMIP6 comparative match, if not, let's just omit them

**Comment by mauzey1** [comment]
@durack1 I have found publications for all of the variables listed.

[global average sea level change](https://cmip-publications.llnl.gov/?type=variable&option=global%20average%20sea%20level%20change)
[mole fraction of ozone in air](https://cmip-publications.llnl.gov/?type=variable&option=mole%20fraction%20of%20ozone%20in%20air)
[northward ocean heat transport due to bolus advection](https://cmip-publications.llnl.gov/?type=variable&option=northward%20ocean%20heat%20transport%20due%20to%20bolus%20advection)
[northward ocean heat transport due to diffusion](https://cmip-publications.llnl.gov/?type=variable&option=northward%20ocean%20heat%20transport%20due%20to%20diffusion)
[sea ice area fraction](https://cmip-publications.llnl.gov/?type=variable&option=sea%20ice%20area%20fraction)
[sea ice thickness](https://cmip-publications.llnl.gov/?type=variable&option=sea%20ice%20thickness)
[sea ice transport across line](https://cmip-publications.llnl.gov/?type=variable&option=sea%20ice%20transport%20across%20line)
[sea ice x velocity](https://cmip-publications.llnl.gov/?type=variable&option=sea%20ice%20x%20velocity)
[sea ice y velocity](https://cmip-publications.llnl.gov/?type=variable&option=sea%20ice%20y%20velocity)
[sea surface temperature](https://cmip-publications.llnl.gov/?type=variable&option=sea%20surface%20temperature)
[sea water potential density](https://cmip-publications.llnl.gov/?type=variable&option=sea%20water%20potential%20density)
[surface downward x stress](https://cmip-publications.llnl.gov/?type=variable&option=surface%20downward%20x%20stress)
[surface downward y stress](https://cmip-publications.llnl.gov/?type=variable&option=surface%20downward%20y%20stress)
[time](https://cmip-publications.llnl.gov/?type=variable&option=time)
[water evaporation flux](https://cmip-publications.llnl.gov/?type=variable&option=water%20evaporation%20flux)

Even [`Other`](https://cmip-publications.llnl.gov/?type=variable&option=Other) has some publications listed for it.  Although I got rid of that variable, the publications should remain in the database and still be accessible.

**Comment by mauzey1** [comment]
@durack1 I've mapped all of the CMIP5 variables to their CMIP6 equivalents.  I think that should cover all of the changes for this issue.

**Comment by mauzey1** [comment]
@durack1 The changes are now live on the site.

**Comment by durack1** [comment]
@mauzey1 excellent, thanks will take a peek soon and aim to finalize and send the announcement early next week

**Comment by durack1** [comment]
@mauzey1 perfect, exactly what we were chasing. Great will get back onto this announcement email and send asap

**Comment by durack1** [comment]
@mauzey1 I have just taken a quick look at the submission page and it seems that the "tos" variable is not listed, see below
![Screenshot_2021-06-09 New Publication](https://user-images.githubusercontent.com/3229632/121429155-7219c400-c92b-11eb-8c7f-b64e24e15295.png)

Just wondering if anything else is missing?

**Comment by mauzey1** [comment]
@durack1 I just applied the change to add the variable to the database.  Please try looking at it again.

**Comment by durack1** [comment]
@mauzey1 excellent, yep it's now there. Just wondering is this a solitary case of a missing variable or are there others?

**Comment by mauzey1** [comment]
@durack1 I've discovered that there is a CMIP6 variable named `prra` that is listed for different modeling realms and has different long names.

- prra - Rainfall Flux
- prra - Rainfall Flux over Land
- prra - Rainfall Flux over Land Ice
- prra - Rainfall Flux where Ice Free Ocean over Sea

The site currently lists `prra - Rainfall Flux where Ice Free Ocean over Sea`.  Should we lists all combinations of out_name and long_name?  The standard_name, `rainfall_flux`, is constant between all versions.  Should we use standard_name instead of long_name?

**Comment by taylor13** [comment]
this is disturbing.  If true, that means file names won't be unique.  I'll check into this further.

**Comment by mauzey1** [comment]
@taylor13 I found one instance of the `prra` variable in different tables.  If you are referring to the data set files, then they should have unique names since they combine both table and variable names.

**Comment by taylor13** [comment]
Yes, that's correct, so this won't be a problem; sorry to raise an alarm.  prra appears in several different tables with different definitions; not ideal, but doesn't break anything.
For the purposes of the publication site, I don't think we need to distinguish between the different variants of prra.

**Comment by durack1** [comment]
@mauzey1 the IM number `LLNL-WEB-823400` has just landed, so it would be great if we can update the footer and close out this issue (I think we have everything solved once that is updated, no?)
