### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by James-Crean** [aims-group/publication-site#42]
Attempting to reset a password does not work, no email is sent/received.

SMTP server/settings need to be added.

**Comment by mattben** [comment]
wat so email was needed! we'll configure the server after lunch

**Comment by taylor13** [comment]
Yesterday I tried to reset my password and didn't receive a message, so even though I *thought* I already had an account, I opened a new account.  Do you think I now have 2 accounts?  Perhaps my old account got replaced with the new account.  What happens if a user tries to open an account with a user name and/or email address the same as an old account.  I think he should be informed that he already has an account.  Is this what happens?  
thanks, Karl

**Comment by mattben** [comment]
Look like you found a bug. I know the system will not allow the same email or user name to create an account. If a user attempts to reset their password but does not have an account we should inform them their to create an account. I'm working on configuring the mail server now.

**Comment by doutriaux1** [comment]
The @taylor13 that already exisited is at: https://github.com/orgs/PCMDI/people/taylor13
So I think you just re-activated your user or something.

**Comment by mattben** [comment]
@doutriaux1 This is in reference to the users for the https://cmip-publications.llnl.gov site. @taylor13 i'm waiting on Tony to fix the email config issues with rainbow1.

**Comment by James-Crean** [comment]
Fixed by setting the smtp options to use the lab email server.
