### ISSUE TITLE
registration required?

### ISSUE THREAD

**Issue by taylor13** [aims-group/publication-site#83]
@mauzey1 @durack1   I am apparently registered on the publication site (and my user name and password are stored on my computer so I can submit new articles).  My question is:  Is new registration easy for users?  Are there any gotcha's we should warn people about?  

The IPCC is inquiring about how to record papers on this site, so I have a feeling that over the next few weeks more scientists will become aware of it and try to submit their papers.  Would be good if the registration is as painless as possible.

**Comment by mauzey1** [comment]
@mauzey1 Registration for users requires adding a username, email address, first and last name, and password.  There's also a Google CAPTCHA used to weed out automated submissions.

Registration currently works but the site currently goes to an error page upon completion of registration.  This due to a missing template HTML file for django-registration.  This will be resolved by the changes made in #84.

**Comment by taylor13** [comment]
I was able to successfully register on the test site you set up, but that's probably not a good test on the open site.

**Comment by mauzey1** [comment]
@taylor13 Registering on the open site should be similar to that of the test site.  Did you or others experience any difficulties in registering on cmip-publications.llnl.gov?

**Comment by taylor13** [comment]
If you've corrected the error alluded to in https://github.com/aims-group/publication-site/issues/83#issuecomment-624972636, then I think everything is fine and we can close this issue.

**Comment by mauzey1** [comment]
Yes, that issue was resolved by merging #84.
