### ISSUE TITLE
Entering "Project" information

### ISSUE THREAD

**Issue by taylor13** [aims-group/publication-site#97]
When registering a publication, we ask the author to indicate the project.  We've agreed that for the next release, "AIMS" should be removed as an option, and only CMIP5 and CMIP6 would be options.  I think we should also provide a little guidance to the authors, perhaps displaying in a smaller font next to the "Projects" heading: "To indicate which data were used in your paper, please select CMIP5, CMIP6 or both (if you analyzed data from both eras)."

If only a single project were selected the choices of data characteristics (the user will need to select in the next section) would be displayed relevant to that project alone.

If only 1 project were selected, I think we should display the following guidance:

"Please select the models, experiments, and other characteristics that describe the data used in your study."   [the list of characteristics shown would be appropriate to the single project; characteristics unique to the other project would be hidden.]

If both CMIP5 and CMIP6 were selected, I don't think any characteristics should be listed initially.  Instead I would like to provide a little more guidance on how to proceed, such as: 

"Please do the following:
1) click on the CMIP5 tab and select the models, experiments, and other characteristics that describe the CMIP5 data used in your study.
2) click on the CMIP6 tab and make appropriate selections for CMIP6 data.  

Should we indicate somewhere that this information is optional?

**Comment by durack1** [comment]
@taylor13 it might be easier to just allow a submission WITHOUT all the additional information to be added, we're not checking it anyway, so it'd be arbitrary to claim that is compulsory. We also want users to provide this info, so rather than offering a get out of jail card (not required), rather let's just leave that unsaid. ok?

**Comment by taylor13** [comment]
I assumed we would allow submission without the bottom-most portion of the form filled out,  although I think we must require the "Project" to be selected.  

I also don't think we really need to point out that the bottom portion is optional.

**Comment by taylor13** [comment]
Thanks for upgrading to "In Progress".  I think this is the last item to take care of before we can beta-test the service with friendly (LLNL) users.  I'm betting that will go well, and we can then advertise it widely.  That will be a real milestone achieved.

**Comment by mauzey1** [comment]
I have added a message that will appear after selecting any of the projects.  I have also made it so that the facets will only appear after selecting a project.

Before selecting a project:
![Screenshot_2020-10-13 New Publication](https://user-images.githubusercontent.com/42009431/95918737-30ffee80-0d61-11eb-81a4-2841bdd1d6a5.png)

After selecting a project:
![Screenshot_2020-10-13 New Publication(1)](https://user-images.githubusercontent.com/42009431/95918795-47a64580-0d61-11eb-9afb-0e7611d5a095.png)

**Comment by taylor13** [comment]
What a good idea! Thanks.

**Comment by taylor13** [comment]
I think this looks good.  I'll close it.
